### PR TITLE
Resolve install hook failures, add Copyright, and add icon

### PR DESCRIPTION
**Pull request by arosales**
http://paste.ubuntu.com/18126079/
- syntax usage on configure()

http://paste.ubuntu.com/18126330/
- In my testing I needed to install gnupg-curl before retriving keys over hkps

> gnupg-curl contains the keyserver helper tools built with libcurl, which replace the ones in the gnupg package built with the "curl shim" variant of gnupg. This package provides support for HKPS keyservers.

```
new file:   copyright
new file:   icon.svg
modified:   lib/charms/layer/mongodb.py
modified:   reactive/mongodb.py
```

### CODE REVIEW

**Comment by marcoceppi** [comment]
This looks good, the only change I would make is removing apt install and instead putting the following in layer.yaml

```
options:
  basic:
    packages:
      - gnupg-curl
```

LGTM with this one change :+1:

**Comment by arosales** [comment]
Good thought, I mainly needed gnupg-curl to be available _before_ key retrieval. I tested this on system z, and the key retrieval functioned correctly with the package being defined in layer.yaml. Thanks for the suggestion @marcoceppi

**Comment by marcoceppi** [comment]
Thanks!

**Comment by marcoceppi** [comment]
Available in cs:~marcoceppi/mongodb-1

**Pull request merged**
